name: Sonderfilm.me
favicon: null
layout_spectrum: 0.06119770999066532
typography_spectrum: 0.25371
title: SONDER n - The Profound realisation that each and every passer by is living a life as vivid and complex as your own
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7db'
    - '#361d0b'
    - '#d19b73'
    - '#9f6116'
    - '#bf3e24'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
